<a href="https://colab.research.google.com/github/francuzovd/higher_mathematics/blob/master/HW_lesson_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Практическое задание 6.

1. Решите линейную систему:

In [2]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
X = np.linalg.solve(A, B)
print(f'Решение уравнения - {X}')

Решение уравнения - [-9.2         0.9         6.46666667]


In [3]:
A1 = np.linalg.inv(A)
X1 = np.dot(A1, B)
print(f'Решение уравнения = {X1}')

Решение уравнения = [-9.2         0.9         6.46666667]


2. Найдите псевдорешение:

$$x + 2y – z = 1$$
$$3x – 4y = 7$$
$$8x – 5y + 2z = 12$$
$$2x – 5z = 7$$
$$11x +4y – 7z = 15$$

In [4]:
A = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
B = np.array([1, 7, 12, 7, 15])
np.linalg.lstsq(A, B)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until


(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

*Ответ:* [1.13919353, -0.90498444, -0.9009803]

3. Сколько решений имеет линейная система:

In [14]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[12, 2, 1]])
C = np.concatenate((A, B.T), axis=1)
print(C)

np.linalg.matrix_rank(A), np.linalg.matrix_rank(C)

[[ 1  2  3 12]
 [ 4  5  6  2]
 [ 7  8  9  1]]


(2, 3)

Т.к. ранг исходной матрицы не равен рангу расширенной матрицы, то система не имеет решений.

In [47]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[12, 12, 12]])
C = np.concatenate((A, B.T), axis=1)
print(C)

np.linalg.matrix_rank(A), np.linalg.matrix_rank(C)

[[ 1  2  3 12]
 [ 4  5  6 12]
 [ 7  8  9 12]]


(2, 2)

In [50]:
np.linalg.lstsq(A, B.T)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


(array([[-6.0000000e+00],
        [ 8.8817842e-16],
        [ 6.0000000e+00]]),
 array([], dtype=float64),
 2,
 array([1.68481034e+01, 1.06836951e+00, 4.41842475e-16]))