In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Практическое задание к уроку 5.

### Задание 1.


In [2]:
A = np.array([[0, 3, 5, 11]])
B = np.array([[2], [6], [10], [22]])

In [3]:
A

array([[ 0,  3,  5, 11]])

In [4]:
B

array([[ 2],
       [ 6],
       [10],
       [22]])

In [5]:
A.shape, B.shape

((1, 4), (4, 1))

In [6]:
A * 2

array([[ 0,  6, 10, 22]])

In [7]:
B + 1

array([[ 3],
       [ 7],
       [11],
       [23]])

In [8]:
np.add(A, B)

array([[ 2,  5,  7, 13],
       [ 6,  9, 11, 17],
       [10, 13, 15, 21],
       [22, 25, 27, 33]])

In [9]:
A + B

array([[ 2,  5,  7, 13],
       [ 6,  9, 11, 17],
       [10, 13, 15, 21],
       [22, 25, 27, 33]])

In [10]:
np.subtract(A, B)

array([[ -2,   1,   3,   9],
       [ -6,  -3,  -1,   5],
       [-10,  -7,  -5,   1],
       [-22, -19, -17, -11]])

In [11]:
A - B

array([[ -2,   1,   3,   9],
       [ -6,  -3,  -1,   5],
       [-10,  -7,  -5,   1],
       [-22, -19, -17, -11]])

In [12]:
np.transpose(B)

array([[ 2,  6, 10, 22]])

In [13]:
np.transpose(A)

array([[ 0],
       [ 3],
       [ 5],
       [11]])

In [14]:
np.dot(A, B)

array([[310]])

In [15]:
np.dot(B, A)

array([[  0,   6,  10,  22],
       [  0,  18,  30,  66],
       [  0,  30,  50, 110],
       [  0,  66, 110, 242]])

In [16]:
C = np.identity(4)
C

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.dot(A, C)

array([[ 0.,  3.,  5., 11.]])

In [18]:
np.dot(C, B)

array([[ 2.],
       [ 6.],
       [10.],
       [22.]])

Построить обратную матрицу для векторов А и В нельзя.

### Задание 2.

\begin{equation}
(5E)^{-1} = 5 * \begin{bmatrix}
1&0&0&0&0\\
0&1&0&0&0\\
0&0&1&0&0\\
0&0&0&1&0\\
0&0&0&0&1\\
\end{bmatrix} = \begin{bmatrix}
5&0&0&0&0\\
0&5&0&0&0\\
0&0&5&0&0\\
0&0&0&5&0\\
0&0&0&0&5\\
\end{bmatrix} = \begin{bmatrix}
0.2&0&0&0&0\\
0&0.2&0&0&0\\
0&0&0.2&0&0\\
0&0&0&0.2&0\\
0&0&0&0&0.2\\
\end{bmatrix}
\end{equation}

### Задание 3.

\begin{equation}
det \begin{bmatrix}
1&2&3\\
4&0&6\\
7&8&9\\
\end{bmatrix} = - det \begin{bmatrix}
4&0&6\\
1&2&3\\
7&8&9\\
\end{bmatrix} = - 4 * \begin{bmatrix}
2&3\\
8&9\\
\end{bmatrix} + 0 * \begin{bmatrix}
1&3\\
7&9\\
\end{bmatrix} + 6 * \begin{bmatrix}
2&3\\
8&9\\
\end{bmatrix} = -4(2*9 -3*8) + 6(2*9 - 3*8)=\\
=-4(18 - 24) - 6(18 - 24) = 24 + 36 = 60\\
\end{equation}

_Ответ: 60_

### Задание 4.


\begin{equation}
\begin{bmatrix}
1&2&3\\
4&0&6\\
7&8&9\\
\end{bmatrix}^{-1} = \begin{bmatrix}
1&4&7\\
2&0&8\\
3&6&9\\
\end{bmatrix}
\end{equation}

In [36]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
A.T

array([[1, 4, 7],
       [2, 0, 8],
       [3, 6, 9]])

### Задание 5.
Приведтите пример матрицы 4х4, ранг которой равен 1.

\begin{bmatrix}
1&2&1&1\\
1&2&1&1\\
1&2&1&1\\
1&2&1&1\\
\end{bmatrix}

In [43]:
B = np.array([[1, 2, 1, 1], [1, 2, 1, 1], [1, 2, 1, 1], [1, 2, 1, 1]])
np.linalg.matrix_rank(B, 0.001)

1

### Задание 6.

$A = (5, 6)$

$B = (2, 8)$

$A * B = 5 * 2 + 6 * 8 = 58$

In [49]:
A = np.array([5, 6])
B = np.array([2, 8])
np.dot(A, B)

58